"""user table

Revision ID: f24133981216
Revises: 27b4f48d0c65
Create Date: 2021-04-24 13:48:48.612556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24133981216'
down_revision = '27b4f48d0c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('passwordhash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_passwordhash'), 'account', ['passwordhash'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('question',
    sa.Column('QuestionID', sa.Integer(), nullable=False),
    sa.Column('Questionbody', sa.String(length=1000), nullable=True),
    sa.Column('Questionanswer', sa.String(length=500), nullable=True),
    sa.Column('creatorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['account.id'], ),
    sa.PrimaryKeyConstraint('QuestionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_passwordhash'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
